/**
 * Vendors the three brand families into the package as woff2 + @font-face.
 *
 * The design system has to ship its own type: anything built with it renders
 * wherever the design tool puts it, with no <link> in a <head> we control, and a
 * fallback face silently undoes the whole typographic system. All three families
 * are SIL Open Font License, so redistributing them here is fine.
 *
 * Latin subset only — the product ships in English, and the cyrillic/vietnamese
 * subsets would roughly triple the payload for glyphs nothing renders.
 *
 *   node scripts/fetch-fonts.mjs
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, '..', 'src', 'styles', 'fonts');

const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Archivo:wght@400;500;600' +
  '&family=Instrument+Sans:wght@400;500;600' +
  '&family=Martian+Mono:wght@400;500;600' +
  '&display=swap';

const slug = (family) => `${family.toLowerCase().replace(/\s+/g, '-')}.woff2`;

const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then((r) => {
  if (!r.ok) throw new Error(`google fonts css: ${r.status}`);
  return r.text();
});

// Emitted as `/* subset */\n@font-face { … }`, one block per subset per weight.
const wanted = [];
const BLOCK = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
for (const [, sub, body] of css.matchAll(BLOCK)) {
  if (sub !== 'latin') continue;
  const family = body.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = body.match(/font-weight:\s*(\d+)/)?.[1];
  const url = body.match(/url\(([^)]+)\)\s*format\('woff2'\)/)?.[1];
  const range = body.match(/unicode-range:\s*([^;]+);/)?.[1];
  const stretch = body.match(/font-stretch:\s*([^;]+);/)?.[1];
  if (!family || !weight || !url) continue;
  wanted.push({ family, weight: Number(weight), url, range, stretch });
}

if (!wanted.length) throw new Error('no latin faces parsed — did the CSS format change?');

await mkdir(OUT, { recursive: true });

// All three families are variable fonts: Google serves ONE woff2 per family
// covering the whole weight axis, so the per-weight blocks all point at the same
// URL. Collapse them into one @font-face per family with a weight *range*, or we
// ship the same 34 KB file three times and make the browser pick between three
// identical faces.
const families = new Map();
for (const face of wanted) {
  const entry = families.get(face.family) ?? { ...face, weights: [] };
  entry.weights.push(face.weight);
  if (entry.url !== face.url) {
    throw new Error(`${face.family}: multiple woff2 urls — not a single variable file, handle statics`);
  }
  families.set(face.family, entry);
}

const rules = [];
for (const face of families.values()) {
  const file = slug(face.family);
  const bytes = Buffer.from(await fetch(face.url, { headers: { 'User-Agent': UA } }).then((r) => {
    if (!r.ok) throw new Error(`${file}: ${r.status}`);
    return r.arrayBuffer();
  }));
  await writeFile(join(OUT, file), bytes);

  const lo = Math.min(...face.weights);
  const hi = Math.max(...face.weights);
  console.log(`${file}  ${(bytes.length / 1024).toFixed(1)} KB  weight ${lo}–${hi}`);

  rules.push(
    [
      '@font-face {',
      `  font-family: '${face.family}';`,
      `  font-style: normal;`,
      `  font-weight: ${lo === hi ? lo : `${lo} ${hi}`};`,
      face.stretch ? `  font-stretch: ${face.stretch};` : null,
      `  font-display: swap;`,
      `  src: url('./fonts/${file}') format('woff2');`,
      face.range ? `  unicode-range: ${face.range};` : null,
      '}',
    ]
      .filter(Boolean)
      .join('\n'),
  );
}

const header = `/* ============================================================================
   Crosses — brand type, vendored.

   Generated by scripts/fetch-fonts.mjs. Latin subset, woff2 only.
   Archivo, Instrument Sans and Martian Mono are all SIL Open Font License.

   Archivo         display — the hero, section headings, the timer, the count
   Instrument Sans body    — everything you actually read
   Martian Mono    labels  — eyebrows, stamps, status, fine print
   ========================================================================= */

`;

await writeFile(join(OUT, '..', 'fonts.css'), header + rules.join('\n\n') + '\n');
console.log(`\n${wanted.length} faces -> src/styles/fonts.css`);
